### ISSUE TITLE
linked list updates are not thread safe

### ISSUE THREAD

**Issue by cockcrow** [jlhutch/pylru#18]
Got error in multi-threading usage.

Found py3 has built-in lru cache. See https://hg.python.org/cpython/file/3.5/Lib/functools.py#l438

**Comment by AndreLouisCaron** [comment]
I use this in asyncio-based server programs which would be negatively impacted by adding locks.  If you intend on the cache thread-safe, please do so in a way that doesn't impact performance for applications that don't use threads (e.g. by adding a derived `threadsafe_lrucache` class that uses a lock to synchronize cache access).

**Comment by jlhutch** [comment]
Pylru has never claimed to be thread safe. Based on the comments here, I am guessing that there is not a huge demand for a synchronized version. If that changes in the future, someone can open this issue again as a feature request. In such a case, a synchronized version would be added as a separate class, so as not to impact the performance of current users.
