### ISSUE TITLE
cached.keys only return a few keys

### ISSUE THREAD

**Issue by xjianster** [jlhutch/pylru#21]
The function cached.keys returns only partial keys, and many repetitions.

**Comment by jlhutch** [comment]
Without more information it is difficult to say what is going wrong. Assuming that you have observed the warning starting on line 57 of readme.txt, will you give the shortest piece of code that reproduces the problem.

**Comment by jlhutch** [comment]
There doesn't seem to be any problem here. Unless someone can reproduce the problem, I am closing the issue.
