### ISSUE TITLE
Next release (1.0.10)?

### ISSUE THREAD

**Issue by spumer** [jlhutch/pylru#24]
Can you upload new release with improvements to pypi?

**Comment by jlhutch** [comment]
I would be happy to bump the release number and update PyPI.

Right now the only functional difference between the 1.0.9 release on PyPI and the master branch on GitHub is the addition of the update() method to pylru. If you need that functionality specifically, let me know, and I will update PyPI sooner than later.

**Comment by spumer** [comment]
Github version has good optimization for `get` method: https://github.com/jlhutch/pylru/pull/20

And i suggest some small improvement for next release:
https://github.com/jlhutch/pylru/pull/25

**Comment by jlhutch** [comment]
I just received your pull notification. I'll take a look. Thanks.

**Comment by jlhutch** [comment]
I uploaded the 1.1.0 release to PyPI. It should have what you need. Let me know if there are any problems.

**Comment by spumer** [comment]
Thank you!
