### ISSUE TITLE
No mention about manager's cache property in docs

### ISSUE THREAD

**Issue by Maboroshy** [jlhutch/pylru#27]
I really like your project. I was reading docs, trying stuff and stuck on obtaining control over cache of manager objects, particularly `FunctionCacheManager`.

It took me a while to understand that manager objects have `cache` property. My IDE didn't show it. I haven't found a mention about it in docs. Reading docs my first though was that `FunctionCacheManager` has nothing more than `size()` and `clear()`.

I think that this a core feature of the project, and clearly writing it in docs could ease the understanding of the project capabilities.

**Comment by jlhutch** [comment]
Just closing old issues that, for whatever reason, never went anywhere. Please feel free to open the issue again if there is still something that needs resolved. Thanks.
