### ISSUE TITLE
Cannot use copy.deepcopy with pylru objects

### ISSUE THREAD

**Issue by 0xDEC0DE** [jlhutch/pylru#31]
# Steps to reproduce

A simple demonstration:

```
import pylru
from copy import deepcopy
herp = pylru.lrucache(size=1024)
derp = deepcopy(herp)
```

# Expected result

A copy of the `lrucache` object, or the lvalue bound to the original

# Actual behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)

<...snip ...>

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/copy.py", line 137, in deepcopy
    d = id(x)
RecursionError: maximum recursion depth exceeded while calling a Python object 
```

# Workaround

A simple subclass of `pylru.lrucache` that returns a pointer to the original on deepcopy operations gets me where I'd like to be:

```
class LRUCache(pylru.lrucache):
    def __deepcopy__(self, memodict=None):
        return self
```

# Errata

* Actually performing a deepcopy of a cache is madness, I don't think it is something that should be encouraged.
* However, stack traces and `SIGABRT` crashes are similarly bad form.  The software should provide a `lrucache.__deepcopy__` method that either:
1. raises a `NotImplementedError`, `RuntimeError`, or similar, OR
2. returns a pointer back to itself, with the docs explaining that's what it does, OR
3. Both, depending on how the object was initialized (i.e., add a new kwarg to `lrucache.__init__`)

**Comment by jlhutch** [comment]
Yeah, that's definitely broken. I agree with you that deepcopy() probably doesn't have a lot of good use cases for the cache. Nevertheless, I'm inclined to fix it rather than mark it as unimplemented and let developers decide for themselves. I will push an update that implements __getstate__() and __setstate__(). That should be enough to fix deepcopy(). It should also fix copy() (i.e. shallow copy) and pickle, both of which are surely broken as well.

**Comment by 0xDEC0DE** [comment]
It's your house, and therefore your rules, and if it hasn't come up after all this time it's probably not likely to ever come up in the wild, but I would advise strongly against having a functional `deepcopy` as the default behaviour.

I only stumbled upon the fact that it didn't work by accident, and I absolutely did *NOT* want a full copy of the cache object getting made.  If it had quietly "worked" I suspect the resulting failures would have been quite subtle, and I might have made it quite a ways into a dev cycle before figuring it out.  I would argue that the [Principle Of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) dictates that it should fall over by default, with an optional initialization arg that lets people misbehave if they like.  But again, this is your circus, and your monkey, and I don't really get a say.

**Comment by jlhutch** [comment]
I appreciate you raising this issue. The most recent commit fixes the bug you found. copy.deepcopy(), copy.copy(), and the pickle module should now all work, as described in the Python standard library docs, with lrucache objects.

I'm more optimistic than you are that developers may find legitimate uses to deepcopy an lrucache object; in the same way that there are good reasons to deepcopy other container types, like a dict or list, in some cases. Maybe I'm wrong, but I'm not willing to exclude the possibility at this time. I'm willing to revisit the issue in the future, if evidence shows that it's causing broad harm to developers using pylru and no significant use cases exist.
