### ISSUE TITLE
please upload your OpenPGP / gpg public key

### ISSUE THREAD

**Issue by adrelanos** [jlhutch/pylru#33]
Could you please upload your OpenPGP / gpg public key somewhere?

related:
https://github.com/jlhutch/pylru/issues/30

**Comment by jlhutch** [comment]
https://github.com/jlhutch.gpg

**Comment by adrelanos** [comment]
nitpick: That would be `.asc` as a file extension instead of `.gpg`. Because the key is gpg `--armor` (ASCII-armored) (which is preferred) instead of binary format (`.gpg`)

**Comment by adrelanos** [comment]
There's a weird `%` sign in that file. I have never seen that before, doesn't break key import but is a bit strange.

**Comment by jlhutch** [comment]
That's strange. When I point my browser at the provided link I get the standard "-----BEGIN PGP PUBLIC KEY BLOCK-----". There are no '%' characters in the text. Regardless, it sounds like you got the key imported successfully.

**Comment by adrelanos** [comment]
I just got confused by my shell due to the lack of a newline at the end of the file.

**Comment by adrelanos** [comment]
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
